version: '3.8'

services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes: 
      - ./data:/var/lib/postgresql/data
      - ./dataset:/docker-entrypoint-initdb.d
    restart: always

  portfolio:
    image: buerdel/portfolio
    container_name: portfolio
    build: .
    ports: 
     - 3000:3000
    depends_on: 
      - postgres